### ISSUE TITLE
uncaught exception

### ISSUE THREAD

**Issue by printercu** [barc/express-error#2]
```
TypeError: first argument must be a string or Buffer
    at ServerResponse.OutgoingMessage.write (http.js:715:11)
    at ServerResponse.OutgoingMessage.end (http.js:804:16)
    at Object.exports.express3 [as handle] (..../node_modules/express-error/lib/expressError.js:244:18)
    at next (..../node_modules/express/node_modules/connect/lib/proto.js:194:17)
```

it's in

```
    return res.end(stack);
```

**Comment by mgutz** [comment]
Without having reproducible code, this is difficult to track down. By just looking at the code, it seems like the error stack was empty or the property did not exist. I can put a check in for that. Would you mind posting your app.js file which initializes express middleware? I would like to see the order of middleware and where this library was called.

**Comment by printercu** [comment]
``` coffee
(-> # `this` is app
  @set 'port', 3001

  @get '*', (req, res, next) -> next 404

  @use require('express-error').express3
    contextLinesCount: 7
    handleUncaughtException: true

  @listen @set 'port'
  console.log 'Listening on port %d in %s mode', @set('port'), @settings.env
).call (require 'express')()
```

**Comment by mgutz** [comment]
Thanks for the info. Please try

```
npm install express-error@0.0.4-pre
```

**Comment by printercu** [comment]
just fine! thank you!
