### ISSUE TITLE
Source code display is not working under Windows

### ISSUE THREAD

**Issue by redking** [barc/express-error#6]
Hey,

I've launched the example app, as described in the docs, but I can't seem to get the source code display/highlighting to work under Windows (it seems to be working under Ubuntu).

Is this a known issue?

**Comment by mgutz** [comment]
Tried on Windows 7 x64 + node v0.10.6 and is working. Which version of Windows and node are you using?

**Comment by redking** [comment]
Windows 7 x64, node v0.10.13. I'll have one of my colleagues try on their windows and see if its reproducible.

**Comment by redking** [comment]
I tested on two systems
- Mac OSX running the latest version of Node (I can see the formatted source code in the stack trace)
- A Windows 7 other than my own, running Node 0.10.13. 

In the 2nd case, the source code is _not_ visible.

I know the exception is invoked for the purposes of demonstrating the source code formatting but, in case it's different under Windows, I've reproduced it below

``` javascript
at Function.Module._resolveFilename (module.js:338:15)
at Function.Module._load (module.js:280:25)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at exports.index (C:\tmp\express-error\example\routes\errorPage.coffee:3:12)
at callbacks (C:\tmp\express-error\node_modules\express\lib\router\index.js:161:37)
at param (C:\tmp\express-error\node_modules\express\lib\router\index.js:135:11)
at pass (C:\tmp\express-error\node_modules\express\lib\router\index.js:142:5)
at Router._dispatch (C:\tmp\express-error\node_modules\express\lib\router\index.js:170:5)
at Object.router (C:\tmp\express-error\node_modules\express\lib\router\index.js:33:10)
at next (C:\tmp\express-error\node_modules\express\node_modules\connect\lib\proto.js:190:15)
at Object.methodOverride [as handle] (C:\tmp\express-error\node_modules\express\node_modules\connect\lib\middleware\methodOverride.js:37:5)
at next (C:\tmp\express-error\node_modules\express\node_modules\connect\lib\proto.js:190:15)
at multipart (C:\tmp\express-error\node_modules\express\node_modules\connect\lib\middleware\multipart.js:64:37)
at C:\tmp\express-error\node_modules\express\node_modules\connect\lib\middleware\bodyParser.js:57:9
at urlencoded (C:\tmp\express-error\node_modules\express\node_modules\connect\lib\middleware\urlencoded.js:51:37)
at C:\tmp\express-error\node_modules\express\node_modules\connect\lib\middleware\bodyParser.js:55:7
at json (C:\tmp\express-error\node_modules\express\node_modules\connect\lib\middleware\json.js:53:37)
at Object.bodyParser [as handle] (C:\tmp\express-error\node_modules\express\node_modules\connect\lib\middleware\bodyParser.js:53:5)
at next (C:\tmp\express-error\node_modules\express\node_modules\connect\lib\proto.js:190:15)
at Object.logger (C:\tmp\express-error\node_modules\express\node_modules\connect\lib\middleware\logger.js:156:5)
at next (C:\tmp\express-error\node_modules\express\node_modules\connect\lib\proto.js:190:15)
at Object.favicon [as handle] (C:\tmp\express-error\node_modules\express\node_modules\connect\lib\middleware\favicon.js:77:7)
at next (C:\tmp\express-error\node_modules\express\node_modules\connect\lib\proto.js:190:15)
at Object.expressInit [as handle] (C:\tmp\express-error\node_modules\express\lib\middleware.js:31:5)
at next (C:\tmp\express-error\node_modules\express\node_modules\connect\lib\proto.js:190:15)
at Object.query [as handle] (C:\tmp\express-error\node_modules\express\node_modules\connect\lib\middleware\query.js:44:5)
at next (C:\tmp\express-error\node_modules\express\node_modules\connect\lib\proto.js:190:15)
at Function.app.handle (C:\tmp\express-error\node_modules\express\node_modules\connect\lib\proto.js:198:3)
at Server.app (C:\tmp\express-error\node_modules\express\node_modules\connect\lib\connect.js:65:37)
at Server.EventEmitter.emit (events.js:98:17)
at HTTPParser.parser.onIncoming (http.js:2056:12)
at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:120:23)
at Socket.socket.ondata (http.js:1946:22)
at TCP.onread (net.js:525:27)
```

**Comment by mgutz** [comment]
Which version of express?

**Comment by redking** [comment]
3.3.4

I plan to look at the express-error source code properly a little later, but could it be related to Windows backslashes and the regex /(~[^:]+):(\d+):(\d+)/ in expressError.js#39 ?

**Comment by mgutz** [comment]
You're on track, related to regex which looks for the char '~'. I can reproduce using the normal command prompt, I use PowerShell. I'll fix in next couple of days.

**Comment by mgutz** [comment]
My PowerShell environment had HOME set to my home directory. In normal command prompt, USERPROFILE is home directory.   

Commited fix. Published to npm. Please close if it is fixed.

**Comment by redking** [comment]
No, I have the same problem I'm afraid

**Comment by mgutz** [comment]
express-error tries to keep the noise down by only showing source if the file is in a subdirectory of the user's home folder. Try it in say c:\users\USER\tmp

**Comment by redking** [comment]
Yes, it works on a subdir of the USER folder. 

Is the base folder configurable or am I obliged to put all my Express projects under the USER dir? 

Thanks for all your help, incidentally!

**Comment by mgutz** [comment]
Finally :) It is not configurable but I will remove the USER folder check by default and add an option to limit context to the project's cwd.

**Comment by mgutz** [comment]
strange it auto closed based on my comment, please try

**Comment by redking** [comment]
That's working well now, with the latest version. Thanks for your help!
